name: Events Demo 1
on:
  pull_request:
    types: 
      - opened
    branches:
      - main
      #- 'dev-*' #dev-new, dev-this-is-new ** means can have more slashes, * means only one slash
      #- 'feat/**' #feat/new, feat/new/button/red
  workflow_dispatch:
  push:
    branches:
      - main
      #- 'dev-*' #dev-new, dev-this-is-new ** means can have more slashes, * means only one slash
      #- 'feat/**' #feat/new, feat/new/button/red
    paths-ignore:
      - '.github/workflows/*' #ignore changes to workflow files. If changes made in other files and 
                              #at least 1 in workflow files, 
                              #then workflow will still not run.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."